import type { Product, Review } from "./types";

export const products: Product[] = [
  {
    id: "iphone-16-pro-max",
    slug: "iphone-16-pro-max",
    name: "iPhone 16 Pro Max",
    brand: "Apple",
    model: "16 Pro Max",
    tagline: "El poder de la IA en la palma de tu mano.",
    description:
      "El iPhone 16 Pro Max redefine lo que es posible. Con el chip A18 Pro, el sistema de cámara más avanzado que hemos creado y una pantalla Super Retina XDR de 6.9 pulgadas con ProMotion de 120 Hz, este es el smartphone definitivo para quienes no se conforman con menos.",
    price: 1899000,
    originalPrice: 2100000,
    currency: "ARS",
    rating: 4.9,
    reviewCount: 2847,
    badges: ["nuevo", "recomendado", "mejor-camara"],
    colors: [
      { name: "Titanio Natural", hex: "#A89880", available: true },
      { name: "Titanio Negro", hex: "#2C2C2E", available: true },
      { name: "Titanio Blanco", hex: "#F2EDE4", available: true },
      { name: "Titanio Desierto", hex: "#C8A882", available: false },
    ],
    storage: [
      { label: "256 GB", priceModifier: 0, available: true },
      { label: "512 GB", priceModifier: 250000, available: true },
      { label: "1 TB", priceModifier: 550000, available: true },
    ],
    images: [
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&q=90",
      "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=800&q=90",
      "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=800&q=90",
    ],
    thumbnailUrl:
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&q=85",
    specs: [
      { label: "Pantalla", value: "6.9\" OLED ProMotion 120 Hz, 2868×1320" },
      { label: "Chip", value: "A18 Pro — 3 nm" },
      { label: "Cámara", value: "48 MP + 48 MP + 12 MP (ultra-wide)" },
      { label: "Video", value: "4K 120 fps ProRes" },
      { label: "Batería", value: "4685 mAh — hasta 33 h de video" },
      { label: "Carga", value: "27 W cableado · 25 W MagSafe" },
      { label: "RAM", value: "8 GB LPDDR5" },
      { label: "Conectividad", value: "5G · Wi-Fi 7 · Bluetooth 5.3 · NFC" },
      { label: "Dimensiones", value: "163.0 × 77.6 × 8.25 mm" },
      { label: "Peso", value: "227 g" },
      { label: "Resistencia", value: "IP68 — 6 m por 30 min" },
      { label: "Sistema", value: "iOS 18" },
    ],
    highlights: [
      "Cámara con teléfoto 5× óptico",
      "Grabación 4K 120 fps ProRes Log",
      "Pantalla Always-On con ProMotion",
      "Titanio aeroespacial ultraliviano",
      "Control de cámara capacitivo",
      "Apple Intelligence incluido",
    ],
    category: "flagship",
    os: "iOS",
    ram: 8,
    storage_gb: 256,
    camera_mp: 48,
    battery_mah: 4685,
    has5G: true,
    isNew: true,
    isRefurbished: false,
    inStock: true,
    installments: 24,
    installmentPrice: 79125,
  },
  {
    id: "samsung-galaxy-s25-ultra",
    slug: "samsung-galaxy-s25-ultra",
    name: "Galaxy S25 Ultra",
    brand: "Samsung",
    model: "S25 Ultra",
    tagline: "Inteligencia sin límites. Productividad máxima.",
    description:
      "El Galaxy S25 Ultra combina el poder del Galaxy AI con el rendimiento del Snapdragon 8 Elite y el S Pen integrado. Una pantalla de 6.9 pulgadas Dynamic AMOLED 2X a 120 Hz y un sistema de cámaras de 200 MP hacen de este smartphone la herramienta definitiva para creativos y profesionales.",
    price: 1750000,
    originalPrice: 1950000,
    currency: "ARS",
    rating: 4.8,
    reviewCount: 1923,
    badges: ["nuevo", "gaming", "mejor-camara"],
    colors: [
      { name: "Titanio Negro", hex: "#1C1C1E", available: true },
      { name: "Titanio Gris", hex: "#8D8D8D", available: true },
      { name: "Titanio Azul", hex: "#3A5B7A", available: true },
      { name: "Titanio Naranja", hex: "#C4602E", available: true },
    ],
    storage: [
      { label: "256 GB", priceModifier: 0, available: true },
      { label: "512 GB", priceModifier: 200000, available: true },
      { label: "1 TB", priceModifier: 450000, available: false },
    ],
    images: [
      "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&q=90",
      "https://images.unsplash.com/photo-1605236453806-6ff36851218e?w=800&q=90",
      "https://images.unsplash.com/photo-1546054454-aa26e2b734c7?w=800&q=90",
    ],
    thumbnailUrl:
      "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600&q=85",
    specs: [
      { label: "Pantalla", value: "6.9\" Dynamic AMOLED 2X, 3088×1440, 120 Hz" },
      { label: "Chip", value: "Snapdragon 8 Elite — 3 nm" },
      { label: "Cámara", value: "200 MP + 50 MP + 10 MP + 50 MP (ultra-wide)" },
      { label: "Video", value: "8K 30 fps · 4K 120 fps" },
      { label: "Batería", value: "5000 mAh — hasta 27 h" },
      { label: "Carga", value: "45 W cableado · 15 W inalámbrico" },
      { label: "RAM", value: "12 GB LPDDR5X" },
      { label: "Conectividad", value: "5G · Wi-Fi 7 · Bluetooth 5.4 · NFC" },
      { label: "Dimensiones", value: "162.8 × 79.0 × 8.2 mm" },
      { label: "Peso", value: "218 g" },
      { label: "Resistencia", value: "IP68 — armadura de titanio" },
      { label: "Sistema", value: "Android 15 · One UI 7" },
    ],
    highlights: [
      "S Pen integrado con Air Actions",
      "Cámara periscópica 5× óptico",
      "Galaxy AI con IA generativa",
      "Pantalla de 120 Hz siempre activa",
      "Armadura de titanio Corning Gorilla Armor 2",
      "Circle to Search con Google",
    ],
    category: "flagship",
    os: "Android",
    ram: 12,
    storage_gb: 256,
    camera_mp: 200,
    battery_mah: 5000,
    has5G: true,
    isNew: true,
    isRefurbished: false,
    inStock: true,
    installments: 24,
    installmentPrice: 72917,
  },
  {
    id: "google-pixel-9-pro-xl",
    slug: "google-pixel-9-pro-xl",
    name: "Pixel 9 Pro XL",
    brand: "Google",
    model: "9 Pro XL",
    tagline: "La IA más inteligente. La cámara más pura.",
    description:
      "El Pixel 9 Pro XL lleva la fotografía computacional al siguiente nivel. Con el chip Google Tensor G4 y las últimas capacidades de IA Gemini integradas directamente al hardware, capturás momentos perfectos incluso en condiciones imposibles.",
    price: 1350000,
    originalPrice: undefined,
    currency: "ARS",
    rating: 4.7,
    reviewCount: 892,
    badges: ["nuevo", "mejor-camara", "recomendado"],
    colors: [
      { name: "Obsidian", hex: "#1A1A1A", available: true },
      { name: "Porcelain", hex: "#F0EBE3", available: true },
      { name: "Hazel", hex: "#8D9C7F", available: true },
      { name: "Rose Quartz", hex: "#E8C5C0", available: false },
    ],
    storage: [
      { label: "128 GB", priceModifier: 0, available: true },
      { label: "256 GB", priceModifier: 120000, available: true },
      { label: "512 GB", priceModifier: 280000, available: true },
      { label: "1 TB", priceModifier: 520000, available: false },
    ],
    images: [
      "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&q=90",
      "https://images.unsplash.com/photo-1609692814858-f7cd2f0afa4f?w=800&q=90",
    ],
    thumbnailUrl:
      "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=600&q=85",
    specs: [
      { label: "Pantalla", value: "6.8\" LTPO OLED, 3120×1440, 1-120 Hz" },
      { label: "Chip", value: "Google Tensor G4" },
      { label: "Cámara", value: "50 MP + 48 MP + 48 MP teleobjetivo" },
      { label: "Video", value: "8K · 4K 60 fps" },
      { label: "Batería", value: "5060 mAh" },
      { label: "Carga", value: "37 W cableado · 23 W inalámbrico" },
      { label: "RAM", value: "16 GB LPDDR5" },
      { label: "Conectividad", value: "5G · Wi-Fi 7 · Bluetooth 5.3" },
      { label: "Sistema", value: "Android 15 — 7 años de actualizaciones" },
    ],
    highlights: [
      "Gemini AI nativo con Pixel Screenshots",
      "Magic Eraser y Photo Unblur IA",
      "Grabación de temperatura y lectores de temperatura",
      "7 años de actualizaciones de Android",
      "Llamadas de pantalla anti-spam",
      "Night Sight con modo astrofotografía",
    ],
    category: "flagship",
    os: "Android",
    ram: 16,
    storage_gb: 128,
    camera_mp: 50,
    battery_mah: 5060,
    has5G: true,
    isNew: true,
    isRefurbished: false,
    inStock: true,
    installments: 18,
    installmentPrice: 75000,
  },
  {
    id: "samsung-galaxy-z-fold-6",
    slug: "samsung-galaxy-z-fold-6",
    name: "Galaxy Z Fold 6",
    brand: "Samsung",
    model: "Z Fold 6",
    tagline: "Dos mundos. Un dispositivo. Sin compromiso.",
    description:
      "El Galaxy Z Fold 6 es el plegable más refinado de Samsung. Con una pantalla interior de 7.6 pulgadas, el Snapdragon 8 Gen 3 y un diseño más delgado y liviano, es la tableta que cabe en tu bolsillo.",
    price: 2200000,
    currency: "ARS",
    rating: 4.6,
    reviewCount: 445,
    badges: ["nuevo", "gaming"],
    colors: [
      { name: "Silver Shadow", hex: "#B8B8B8", available: true },
      { name: "Navy", hex: "#1A2744", available: true },
      { name: "Pink", hex: "#D4A0A8", available: true },
    ],
    storage: [
      { label: "256 GB", priceModifier: 0, available: true },
      { label: "512 GB", priceModifier: 300000, available: true },
      { label: "1 TB", priceModifier: 650000, available: false },
    ],
    images: [
      "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&q=90",
      "https://images.unsplash.com/photo-1588702547923-7093a6c3ba33?w=800&q=90",
    ],
    thumbnailUrl:
      "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&q=85",
    specs: [
      { label: "Pantalla interior", value: "7.6\" Dynamic AMOLED 2X, 120 Hz" },
      { label: "Pantalla exterior", value: "6.3\" Dynamic AMOLED 2X, 120 Hz" },
      { label: "Chip", value: "Snapdragon 8 Gen 3" },
      { label: "Cámara", value: "50 MP + 10 MP + 12 MP" },
      { label: "Batería", value: "4400 mAh" },
      { label: "RAM", value: "12 GB" },
      { label: "Conectividad", value: "5G · Wi-Fi 7" },
      { label: "Sistema", value: "Android 14 — One UI 6.1.1" },
    ],
    highlights: [
      "Pantalla interior de 7.6\" pulgadas",
      "Bisagra ultra-delgada y resistente",
      "Multitarea avanzada con ventanas múltiples",
      "IPX8 resistente al agua",
      "S Pen compatible (se vende por separado)",
    ],
    category: "premium",
    os: "Android",
    ram: 12,
    storage_gb: 256,
    camera_mp: 50,
    battery_mah: 4400,
    has5G: true,
    isNew: true,
    isRefurbished: false,
    inStock: true,
    installments: 24,
    installmentPrice: 91667,
  },
  {
    id: "iphone-15",
    slug: "iphone-15",
    name: "iPhone 15",
    brand: "Apple",
    model: "15",
    tagline: "Cámara dinámica. Performance notable.",
    description:
      "El iPhone 15 trae Dynamic Island a la línea base, junto con el chip A16 Bionic y una cámara principal de 48 MP. El conector USB-C lo hace más versátil que nunca.",
    price: 980000,
    originalPrice: 1150000,
    currency: "ARS",
    rating: 4.7,
    reviewCount: 3120,
    badges: ["oferta", "recomendado"],
    colors: [
      { name: "Negro", hex: "#1A1A1A", available: true },
      { name: "Rosa", hex: "#F1D4D4", available: true },
      { name: "Amarillo", hex: "#F6E5A0", available: true },
      { name: "Verde", hex: "#A8C5A0", available: true },
      { name: "Azul", hex: "#A4B8C4", available: true },
    ],
    storage: [
      { label: "128 GB", priceModifier: 0, available: true },
      { label: "256 GB", priceModifier: 130000, available: true },
      { label: "512 GB", priceModifier: 300000, available: true },
    ],
    images: [
      "https://images.unsplash.com/photo-1683130765763-39e47d9e64eb?w=800&q=90",
      "https://images.unsplash.com/photo-1696446701796-da61339e4b5f?w=800&q=90",
    ],
    thumbnailUrl:
      "https://images.unsplash.com/photo-1683130765763-39e47d9e64eb?w=600&q=85",
    specs: [
      { label: "Pantalla", value: "6.1\" Super Retina XDR, 2556×1179, 60 Hz" },
      { label: "Chip", value: "A16 Bionic — 4 nm" },
      { label: "Cámara", value: "48 MP principal + 12 MP ultra-wide" },
      { label: "Batería", value: "3877 mAh" },
      { label: "Carga", value: "20 W · 15 W MagSafe" },
      { label: "RAM", value: "6 GB" },
      { label: "Conectividad", value: "5G · Wi-Fi 6E · Bluetooth 5.3" },
      { label: "Sistema", value: "iOS 17 — actualizable a iOS 18" },
    ],
    highlights: [
      "Dynamic Island exclusivo",
      "USB-C con USB 3 (480 Mbps)",
      "Cámara principal de 48 MP",
      "Modo de acción para video",
      "Crash Detection y Emergency SOS",
    ],
    category: "gama-alta",
    os: "iOS",
    ram: 6,
    storage_gb: 128,
    camera_mp: 48,
    battery_mah: 3877,
    has5G: true,
    isNew: false,
    isRefurbished: false,
    inStock: true,
    installments: 18,
    installmentPrice: 54444,
  },
  {
    id: "xiaomi-14-ultra",
    slug: "xiaomi-14-ultra",
    name: "Xiaomi 14 Ultra",
    brand: "Xiaomi",
    model: "14 Ultra",
    tagline: "Leica. Ultra. Sin compromisos fotográficos.",
    description:
      "El Xiaomi 14 Ultra lleva la colaboración con Leica a su máxima expresión. Cuatro cámaras de 50 MP con óptica Leica variable y el Snapdragon 8 Gen 3 definen una nueva categoría en fotografía móvil.",
    price: 1480000,
    currency: "ARS",
    rating: 4.8,
    reviewCount: 678,
    badges: ["nuevo", "mejor-camara"],
    colors: [
      { name: "Black", hex: "#1A1A1A", available: true },
      { name: "White", hex: "#F5F5F5", available: true },
    ],
    storage: [
      { label: "256 GB", priceModifier: 0, available: true },
      { label: "512 GB", priceModifier: 180000, available: true },
      { label: "1 TB", priceModifier: 400000, available: false },
    ],
    images: [
      "https://images.unsplash.com/photo-1585060544812-6b45742d762f?w=800&q=90",
      "https://images.unsplash.com/photo-1567581935884-3349723552ca?w=800&q=90",
    ],
    thumbnailUrl:
      "https://images.unsplash.com/photo-1585060544812-6b45742d762f?w=600&q=85",
    specs: [
      { label: "Pantalla", value: "6.73\" LTPO AMOLED, 3200×1440, 1-120 Hz" },
      { label: "Chip", value: "Snapdragon 8 Gen 3" },
      { label: "Cámara", value: "4× 50 MP Leica Summilux — apertura variable" },
      { label: "Video", value: "8K 24 fps · 4K 120 fps" },
      { label: "Batería", value: "5300 mAh" },
      { label: "Carga", value: "90 W cableado · 80 W inalámbrico" },
      { label: "RAM", value: "16 GB LPDDR5X" },
      { label: "Conectividad", value: "5G · Wi-Fi 7 · Bluetooth 5.4" },
      { label: "Sistema", value: "Android 14 · HyperOS" },
    ],
    highlights: [
      "4 cámaras Leica 50 MP con apertura variable f/1.63–f/4.0",
      "Carga rápida HyperCharge 90 W",
      "Carga inalámbrica 80 W más rápida del mundo",
      "Pantalla micro-quad-curved LTPO",
      "Modo estudio de video avanzado",
    ],
    category: "flagship",
    os: "Android",
    ram: 16,
    storage_gb: 256,
    camera_mp: 50,
    battery_mah: 5300,
    has5G: true,
    isNew: true,
    isRefurbished: false,
    inStock: true,
    installments: 18,
    installmentPrice: 82222,
  },
  {
    id: "samsung-galaxy-a55",
    slug: "samsung-galaxy-a55",
    name: "Galaxy A55",
    brand: "Samsung",
    model: "A55",
    tagline: "Premium sin romper el presupuesto.",
    description:
      "El Galaxy A55 trae un diseño de nivel flagship a la gama media. Con pantalla AMOLED de 120 Hz, triple cámara de 50 MP y protección IP67, demuestra que no necesitás gastar de más para tener calidad premium.",
    price: 540000,
    originalPrice: 620000,
    currency: "ARS",
    rating: 4.5,
    reviewCount: 4230,
    badges: ["oferta", "recomendado"],
    colors: [
      { name: "Awesome Navy", hex: "#1A2744", available: true },
      { name: "Awesome Lilac", hex: "#C8B8D8", available: true },
      { name: "Awesome Iceblue", hex: "#B0C8DC", available: true },
    ],
    storage: [
      { label: "128 GB", priceModifier: 0, available: true },
      { label: "256 GB", priceModifier: 80000, available: true },
    ],
    images: [
      "https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=800&q=90",
    ],
    thumbnailUrl:
      "https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=600&q=85",
    specs: [
      { label: "Pantalla", value: "6.6\" Super AMOLED, 2340×1080, 120 Hz" },
      { label: "Chip", value: "Exynos 1480 — 4 nm" },
      { label: "Cámara", value: "50 MP + 12 MP + 5 MP" },
      { label: "Batería", value: "5000 mAh" },
      { label: "Carga", value: "25 W" },
      { label: "RAM", value: "8 GB" },
      { label: "Conectividad", value: "5G · Wi-Fi 6 · Bluetooth 5.3" },
      { label: "Sistema", value: "Android 14 · One UI 6.1" },
    ],
    highlights: [
      "Pantalla AMOLED de 120 Hz con corning gorilla glass",
      "Resistencia IP67",
      "Optical Image Stabilization (OIS)",
      "4 años de actualizaciones garantizadas",
      "Slot MicroSD hasta 1 TB",
    ],
    category: "gama-media",
    os: "Android",
    ram: 8,
    storage_gb: 128,
    camera_mp: 50,
    battery_mah: 5000,
    has5G: true,
    isNew: false,
    isRefurbished: false,
    inStock: true,
    installments: 12,
    installmentPrice: 45000,
  },
  {
    id: "motorola-edge-50-pro",
    slug: "motorola-edge-50-pro",
    name: "Edge 50 Pro",
    brand: "Motorola",
    model: "Edge 50 Pro",
    tagline: "Carga ultra-rápida. Diseño icónico.",
    description:
      "El Edge 50 Pro de Motorola ofrece una experiencia premium a un precio inteligente. Con carga de 125 W y una pantalla pOLED curva de 144 Hz, es el smartphone que más impresiona por lo que cuesta.",
    price: 620000,
    currency: "ARS",
    rating: 4.4,
    reviewCount: 1120,
    badges: ["mejor-bateria", "oferta"],
    colors: [
      { name: "Black Beauty", hex: "#1A1A1A", available: true },
      { name: "Luxe Lavender", hex: "#B8A4C8", available: true },
      { name: "Caneel Bay", hex: "#3A5A4A", available: false },
    ],
    storage: [
      { label: "256 GB", priceModifier: 0, available: true },
      { label: "512 GB", priceModifier: 100000, available: true },
    ],
    images: [
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&q=90",
    ],
    thumbnailUrl:
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&q=85",
    specs: [
      { label: "Pantalla", value: "6.7\" pOLED Curved, 2712×1220, 144 Hz" },
      { label: "Chip", value: "Snapdragon 7s Gen 2 — 4 nm" },
      { label: "Cámara", value: "50 MP + 10 MP + 13 MP" },
      { label: "Batería", value: "4500 mAh" },
      { label: "Carga", value: "125 W TurboPower — 0 a 100% en 21 min" },
      { label: "RAM", value: "12 GB" },
      { label: "Conectividad", value: "5G · Wi-Fi 6E · Bluetooth 5.3" },
      { label: "Sistema", value: "Android 14 · My UX — 3 años de SO" },
    ],
    highlights: [
      "Carga de 125 W — completamente cargado en 21 min",
      "Pantalla pOLED curva de 144 Hz",
      "IP68 resistente al agua",
      "Motorizaciones Moto AI",
      "Cámara con apertura variable f/1.4",
    ],
    category: "gama-alta",
    os: "Android",
    ram: 12,
    storage_gb: 256,
    camera_mp: 50,
    battery_mah: 4500,
    has5G: true,
    isNew: false,
    isRefurbished: false,
    inStock: true,
    installments: 12,
    installmentPrice: 51667,
  },
  {
    id: "iphone-14-reacondicionado",
    slug: "iphone-14-reacondicionado",
    name: "iPhone 14 — Reacondicionado",
    brand: "Apple",
    model: "14",
    tagline: "La experiencia Apple a precio accesible.",
    description:
      "iPhone 14 reacondicionado certificado. Batería al 100%, aspecto impecable y garantía de 12 meses. La misma calidad Apple, renovada.",
    price: 690000,
    originalPrice: 850000,
    currency: "ARS",
    rating: 4.6,
    reviewCount: 892,
    badges: ["reacondicionado", "oferta"],
    colors: [
      { name: "Midnight", hex: "#1A1A1A", available: true },
      { name: "Starlight", hex: "#F5F0E8", available: true },
      { name: "Blue", hex: "#A8C0D0", available: true },
    ],
    storage: [
      { label: "128 GB", priceModifier: 0, available: true },
      { label: "256 GB", priceModifier: 100000, available: true },
    ],
    images: [
      "https://images.unsplash.com/photo-1678685888221-cda773a3dcdb?w=800&q=90",
    ],
    thumbnailUrl:
      "https://images.unsplash.com/photo-1678685888221-cda773a3dcdb?w=600&q=85",
    specs: [
      { label: "Pantalla", value: "6.1\" OLED, 2532×1170, 60 Hz" },
      { label: "Chip", value: "A15 Bionic — 5 nm" },
      { label: "Cámara", value: "12 MP + 12 MP ultra-wide" },
      { label: "Batería", value: "3279 mAh — reemplazada al 100%" },
      { label: "Conectividad", value: "5G · Wi-Fi 6 · Bluetooth 5.3" },
      { label: "Sistema", value: "iOS 17" },
    ],
    highlights: [
      "Batería nueva al 100%",
      "Cuerpo verificado sin daños estructurales",
      "Garantía oficial APEX 12 meses",
      "Caja, cable y auriculares incluidos",
      "Testeado con más de 50 pruebas de calidad",
    ],
    category: "reacondicionado",
    os: "iOS",
    ram: 6,
    storage_gb: 128,
    camera_mp: 12,
    battery_mah: 3279,
    has5G: true,
    isNew: false,
    isRefurbished: true,
    inStock: true,
    installments: 12,
    installmentPrice: 57500,
  },
];

export const getProductBySlug = (slug: string): Product | undefined =>
  products.find((p) => p.slug === slug);

export const getFeaturedProducts = (): Product[] =>
  products.filter((p) => p.badges.includes("recomendado") || p.badges.includes("nuevo")).slice(0, 4);

export const getRelatedProducts = (product: Product, limit = 4): Product[] =>
  products
    .filter((p) => p.id !== product.id && (p.brand === product.brand || p.category === product.category))
    .slice(0, limit);

export const reviews: Review[] = [
  {
    id: "r1",
    productId: "iphone-16-pro-max",
    author: "Martín G.",
    avatar: "MG",
    rating: 5,
    date: "2025-11-10",
    title: "Lo mejor que compré en años",
    body: "Llegó en 24hs, el equipo está impecable y la cámara supera todas mis expectativas. El sistema de IA para fotos es increíble. 100% recomendado comprar en APEX.",
    verified: true,
    helpful: 47,
  },
  {
    id: "r2",
    productId: "samsung-galaxy-s25-ultra",
    author: "Laura P.",
    avatar: "LP",
    rating: 5,
    date: "2025-10-22",
    title: "Increíble para trabajar y crear contenido",
    body: "El S Pen hace una diferencia enorme para tomar notas y hacer bocetos. La pantalla es de otro nivel y la batería me dura todo el día con uso intenso. Galaxy AI funciona mejor de lo que esperaba.",
    verified: true,
    helpful: 31,
  },
  {
    id: "r3",
    productId: "iphone-15",
    author: "Diego M.",
    avatar: "DM",
    rating: 4,
    date: "2025-09-15",
    title: "Excelente relación calidad-precio",
    body: "Lo compré durante el Hot Sale con descuento. La cámara de 48 MP saca fotos hermosas de día y de noche. El Dynamic Island lo uso todo el tiempo. Muy satisfecho.",
    verified: true,
    helpful: 22,
  },
  {
    id: "r4",
    productId: "google-pixel-9-pro-xl",
    author: "Ana R.",
    avatar: "AR",
    rating: 5,
    date: "2025-10-05",
    title: "La mejor cámara que usé",
    body: "Llevo años usando iPhones y pasarme al Pixel 9 Pro fue una revelación. Las fotos en modo noche son espectaculares. El asistente de IA es útil de verdad, no como marketing.",
    verified: true,
    helpful: 18,
  },
];

export const testimonials = [
  {
    id: "t1",
    name: "Sebastián Torres",
    role: "Fotógrafo profesional",
    avatar: "ST",
    quote:
      "Compré mi iPhone 16 Pro Max en APEX y la experiencia fue impecable. El proceso fue sencillo, llegó en tiempo y el celular es extraordinario para mi trabajo.",
    rating: 5,
    product: "iPhone 16 Pro Max",
  },
  {
    id: "t2",
    name: "Valentina Cruz",
    role: "Content creator",
    avatar: "VC",
    quote:
      "Me sorprendió la velocidad de entrega y la atención al cliente. El Galaxy S25 Ultra que compré superó todas mis expectativas para crear contenido.",
    rating: 5,
    product: "Galaxy S25 Ultra",
  },
  {
    id: "t3",
    name: "Rodrigo Iglesias",
    role: "Desarrollador de software",
    avatar: "RI",
    quote:
      "Ya van tres compras en APEX y siempre la misma experiencia de primer nivel. Precios transparentes, cuotas reales y entrega puntual.",
    rating: 5,
    product: "Pixel 9 Pro XL",
  },
];

export const brands = [
  { name: "Apple", logo: "🍎", count: 3 },
  { name: "Samsung", logo: "🌀", count: 3 },
  { name: "Google", logo: "🔍", count: 1 },
  { name: "Xiaomi", logo: "✦", count: 1 },
  { name: "Motorola", logo: "⊕", count: 1 },
];

export const categories = [
  {
    id: "camara",
    label: "Mejor Cámara",
    description: "Para los que capturan cada momento",
    icon: "camera",
    badge: "mejor-camara",
  },
  {
    id: "bateria",
    label: "Mayor Batería",
    description: "Todo el día sin preocuparte",
    icon: "battery",
    badge: "mejor-bateria",
  },
  {
    id: "gaming",
    label: "Gaming",
    description: "Performance máxima para jugar",
    icon: "gamepad",
    badge: "gaming",
  },
  {
    id: "precio",
    label: "Mejor Precio",
    description: "Calidad sin gastar de más",
    icon: "tag",
    badge: "oferta",
  },
  {
    id: "trabajo",
    label: "Trabajo",
    description: "Productividad sin límites",
    icon: "briefcase",
    badge: "recomendado",
  },
  {
    id: "contenido",
    label: "Contenido",
    description: "Para creadores de contenido",
    icon: "video",
    badge: "nuevo",
  },
];

export const faqs = [
  {
    q: "¿Cuánto tarda el envío?",
    a: "Todos los pedidos tienen envío express de 24 a 48 horas hábiles a Capital Federal y GBA. Para el interior del país, el plazo es de 3 a 5 días hábiles. Los pedidos realizados antes de las 14hs se despachan el mismo día.",
  },
  {
    q: "¿Cuántas cuotas sin interés tienen disponibles?",
    a: "Ofrecemos hasta 24 cuotas sin interés con tarjetas de crédito de los principales bancos del país. El detalle de cuotas disponibles se muestra en cada producto y durante el checkout.",
  },
  {
    q: "¿Qué garantía tienen los equipos?",
    a: "Todos los equipos nuevos incluyen garantía oficial del fabricante (12 meses). Los equipos reacondicionados incluyen garantía APEX de 12 meses con cobertura completa.",
  },
  {
    q: "¿Puedo devolver un equipo si no estoy conforme?",
    a: "Sí, tenés 30 días desde la compra para devolver el equipo sin costo y sin preguntas si no estás conforme. El reintegro se acredita en tu tarjeta o cuenta en un plazo de 5 días hábiles.",
  },
  {
    q: "¿Los celulares son originales y libres?",
    a: "100%. Todos nuestros equipos son originales, comprados a distribuidores oficiales y completamente libres de fábrica. No vendemos equipos atados a ninguna operadora.",
  },
  {
    q: "¿Tienen programa de trade-in?",
    a: "Sí. Podés entregar tu celular usado a cambio de descuento en tu compra. Completá el formulario de tasación online y recibís una oferta en menos de 30 minutos.",
  },
];

export const formatPrice = (price: number): string =>
  new Intl.NumberFormat("es-AR", {
    style: "currency",
    currency: "ARS",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(price);

export const discountPercent = (original: number, current: number): number =>
  Math.round(((original - current) / original) * 100);
